//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.06 at 09:19:41 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ru.isakov.market/spring/market/ws/productsWs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.isakov.market.soap.products;
